example:
  message: "Hello from Config Server! [Gateway Service]"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: accounts-route
          uri: lb://accounts-service
          predicates:
            - Path=/api/v1/accounts/**
        - id: cash-route
          uri: lb://cash-service
          predicates:
            - Path=/api/v1/cash/**
        - id: transfer-route
          uri: lb://transfer-service
          predicates:
            - Path=/api/v1/transfer/**
        - id: notifications-route
          uri: lb://notifications-service
          predicates:
            - Path=/api/v1/notifications/**
        - id: stub-route
          uri: lb://stub-service
          predicates:
            - Path=/api/v1/fallbacks/**
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus