server:
  port: 8081

spring:
  application:
    name: accounts-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bank
          jwk-set-uri: http://keycloak:8080/realms/bank/protocol/openid-connect/certs


  cloud:
    inetutils:
      ignored-interfaces:
        - VMware.*
        - vbox.*
      preferred-networks:
        - 127.0.0.1
        - localhost
  config:
    import: "optional:configserver:http://config-service:8888"


eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}